// Kits.swift — the kit table, and what a kit is once it has stopped being CSS.
//
// **There is no palette data in this file.** The 16 open kits and the 13 font pairs live in
// `Kits.generated.swift`, which the KitsGen plugin writes at build time out of
// `test/fixtures/kits.json` and `test/fixtures/watch-fonts.json` — the same arrangement as
// `Config.swift` over `GeneratedConfig`, and for the same reason: a colour typed into Swift is a
// colour that can disagree with the one the web renders, and nothing would say so.
//
// Why a fixture and not `theme.js` itself. 62 of the 314 hex tokens in the finished table appear
// nowhere in `theme.js`'s source — every kit has at least one — because they come out of
// `finalize()` → `ensure()` → `oklch()`: cube roots, a 14-iteration gamut search, WCAG contrast and
// a 60-step lightness loop. A Swift plugin that recomputed them would have to match JavaScript
// doubles bit for bit, which is the forbidden second copy of the palette in its worst form. And
// `node` is genuinely unreachable from an Xcode build. So the fixture is generated by hand and
// `KitFixtureTests` is what catches drift: it evaluates live `theme.js` in a `JSContext` and
// compares. That test can never ship to a wrist — `JavaScriptCore` is in the macOS and iOS SDKs and
// absent from watchOS — which is exactly the shape we want.
//
// **The two Secret kits are not here and are not in any binary.** They reach a Watch only from a
// phone whose person has unlocked them, over `WatchLinkPayload.extra`, and they arrive as this same
// `Kit` through `Kit(json:)`. The table below is the 16 anyone can have.
//
// ---------------------------------------------------------------- what crosses, and what does not
//
// `theme.js` gives a kit 26 colour tokens. **16 of them are really `#RRGGBB`** and all 16 are here.
// The other ten are CSS, and a Watch has no CSS:
//
//   * `hair` / `hairHi` are `rgba()` strings, and always an alpha over the kit's own `--text` —
//     asserted by the generator, because Pink writes .16/.42 by hand despite being a dark base, so
//     deriving the alpha from `base` would quietly give Pink the wrong hairline. What crosses is
//     the two alphas; the reader composes `text.opacity(hairAlpha)`.
//   * `glow` is a `radial-gradient(...)`, `strikeShadow` a CSS `box-shadow`, and `boxDoneBg`,
//     `barBg` and `strikeBg` are each a hex **or** a `linear-gradient(...)` depending on the kit.
//     **Dropped.** A gradient is a paint, not a colour, and the three that are sometimes a hex are
//     worse than the three that never are: a type whose meaning changes per kit is a type every
//     call site has to ask about. A Watch that wants the accent already has `accent`, `accentHi`
//     and `accentDeep`, which is what every one of those gradients is made of.
//   * `strikeSize` and `strikeAnim` are CSS animation parameters (`"300% 100%"`,
//     `"shimmer 3.4s linear infinite"`). **Dropped** — SwiftUI has no keyframe named `shimmer`.
//   * `finaleStyle` is `"italic"` or `"normal"`. **Kept**, as `finaleItalic`, because it is one bit
//     and a wrist can honour it.
//
// A kit's sound engine and its parameters are dropped too: the Watch plays haptics, not sound
// (`WKInterfaceDevice.play`, and `CoreHaptics` is still absent from watchOS), so an engine name
// would be a field nothing reads. `field`, `finale` and `finaleText` belong to the two Secret kits
// and travel with them rather than living in a table that does not contain them.
import Foundation

/// Which way a kit's grounds run. `color-scheme` on the web; on a wrist it decides whether
/// `.environment(\.colorScheme, …)` has to be forced, since watchOS has no light appearance of
/// its own.
public enum KitBase: String, Sendable, Hashable, Codable, CaseIterable {
    case dark, light
}

/// Which slot a kit was designed for. Every kit names a `partner` that leans the other way.
public enum KitLean: String, Sendable, Hashable, Codable, CaseIterable {
    case day, night
}

/// The 16 tokens that are really colours, plus the two hairline alphas. Every string is `#RRGGBB`,
/// upper case, exactly as `theme.js` finished it.
public struct KitColors: Sendable, Hashable, Codable {
    /// The page, and the two surfaces above it. `ink3` is the elevated one — panels, filled chips, a
    /// hovered star — and it is the ground the accent floors are measured against.
    public let ink: String, ink2: String, ink3: String
    /// Body text, and the three secondaries on `ink`.
    public let text: String, muted: String, dim: String, done: String
    /// The same three secondaries nudged for `ink3`, which is a different ground and a different floor.
    public let muted2: String, dim2: String, done2: String
    /// The accent family. `accent` clears 3:1 on both grounds (a UI colour); `accentText` clears
    /// 4.5:1 on both (a text colour). They are usually not the same hex and must not be swapped.
    public let accent: String, accentHi: String, accentDeep: String, accentText: String
    public let danger: String
    /// A solid line that clears 3:1 on `ink` — checkbox borders, dividers.
    public let hairSolid: String
    /// `text` at this alpha is the hairline; `hairHiAlpha` is the emphasised one.
    public let hairAlpha: Double, hairHiAlpha: Double

    public init(ink: String, ink2: String, ink3: String,
                text: String, muted: String, dim: String, done: String,
                muted2: String, dim2: String, done2: String,
                accent: String, accentHi: String, accentDeep: String, accentText: String,
                danger: String, hairSolid: String,
                hairAlpha: Double, hairHiAlpha: Double) {
        self.ink = ink; self.ink2 = ink2; self.ink3 = ink3
        self.text = text; self.muted = muted; self.dim = dim; self.done = done
        self.muted2 = muted2; self.dim2 = dim2; self.done2 = done2
        self.accent = accent; self.accentHi = accentHi; self.accentDeep = accentDeep
        self.accentText = accentText
        self.danger = danger; self.hairSolid = hairSolid
        self.hairAlpha = hairAlpha; self.hairHiAlpha = hairHiAlpha
    }
}

/// One face, named the way CoreText will answer to.
///
/// `postScriptName` is the one to ask with. The family names in `theme.js` are the fiction
/// `styles.css`'s `@font-face` rules invent — twelve of the twenty-two resolve to something else on
/// Apple platforms, and a missing custom font renders the system face with no log and no error — so
/// every name here was read back out of the `.ttf` that `apple/tools/gen-watch-fonts.py` produced.
public struct KitFace: Sendable, Hashable, Codable {
    public let postScriptName: String
    public let family: String
    public let weight: Int
    /// The file in `apple/TodaysFive/Fonts/`, which is also its entry in the app's `UIAppFonts`.
    public let file: String

    public init(postScriptName: String, family: String, weight: Int, file: String) {
        self.postScriptName = postScriptName
        self.family = family
        self.weight = weight
        self.file = file
    }
}

/// A font pair: the face task lines are set in, and the face everything else is.
///
/// A task face has exactly **one** weight, because `styles.css` draws it at `var(--task-w)` at every
/// one of its seven call sites and nowhere else. A ui face has the weights its axis string names,
/// which is what the web serves. Every face is a static instance, so `.weight()` never has to
/// resolve anything — measured to be a no-op on Fraunces and Source Serif 4, which carry no `fvar`
/// named instances.
public struct KitType: Sendable, Hashable, Codable {
    /// The pair id in `theme.js` (`"lato"`, `"mono"`, …).
    public let id: String
    /// The pair's display name, "Outfit + Nunito Sans".
    public let name: String
    public let task: KitFace
    /// Lightest first.
    public let ui: [KitFace]
    /// The task line's tracking, in em — `theme.js`'s `ls`, parsed. Multiply by the point size.
    public let tracking: Double
    /// The task line's line height as a multiple of the point size — `theme.js`'s `lh`.
    public let lineHeight: Double

    public init(id: String, name: String, task: KitFace, ui: [KitFace],
                tracking: Double, lineHeight: Double) {
        self.id = id; self.name = name; self.task = task; self.ui = ui
        self.tracking = tracking; self.lineHeight = lineHeight
    }

    /// The ui face for body text.
    public var uiRegular: KitFace { ui.first ?? task }
    /// The ui face for anything emphasised. The same as `uiRegular` when the pair has one weight.
    public var uiBold: KitFace { ui.last ?? task }
}

/// A kit: a palette, a font pair, a confetti set, and which slot it was drawn for.
public struct Kit: Sendable, Hashable, Codable, Identifiable {
    public let id: String
    public let name: String
    public let base: KitBase
    public let lean: KitLean
    /// The id of the kit designed for the other slot. Mutual: `partnerOf(partnerOf(k)) == k`.
    public let partner: String
    /// The font pair's id. `type` resolves it.
    public let pair: String
    /// True only for a kit that arrived from a phone that had unlocked it. Never true in the table.
    public let secret: Bool
    public let colors: KitColors
    /// Five or six `#RRGGBB` the finale throws.
    public let confetti: [String]
    /// Which shapes the finale throws: 1 dot, 2 ribbon, 3 heart/star, 4 the Birthday set — `fx.js`
    /// is the reference. An array because two kits name several.
    public let shapes: [Int]
    /// `theme.js`'s `finaleStyle`. The line under the last struck row is set in italic.
    public let finaleItalic: Bool

    public init(id: String, name: String, base: KitBase, lean: KitLean, partner: String,
                pair: String, secret: Bool, colors: KitColors, confetti: [String],
                shapes: [Int], finaleItalic: Bool) {
        self.id = id; self.name = name; self.base = base; self.lean = lean
        self.partner = partner; self.pair = pair; self.secret = secret
        self.colors = colors; self.confetti = confetti; self.shapes = shapes
        self.finaleItalic = finaleItalic
    }

    /// The faces this kit is set in, or nil for a kit naming a pair this build does not have.
    public var type: KitType? { Kits.type(pair) }
}

// ---------------------------------------------------------------- the table

public enum Kits {

    /// The 16 kits anyone can have, in `theme.js`'s own order. The two Secret kits are not here;
    /// see the file comment.
    public static var open: [Kit] { GeneratedKits.all }

    /// The 13 font pairs, by id. All thirteen, including the two only the Secret kits use — a font
    /// pair is not a secret, and a Secret kit that arrives at runtime has to be able to find its
    /// faces.
    public static var types: [String: KitType] { GeneratedKits.types }

    /// The eight day kits in the order the picker shows them; `night` is the same eight partners in
    /// the same order, so a day kit and its night share an index.
    public static var day: [Kit] { GeneratedKits.dayIds.compactMap(byId) }
    public static var night: [Kit] { GeneratedKits.nightIds.compactMap(byId) }

    /// What a device that has never chosen gets: Paper by day, Terminal by night, since 1.11.
    public static var defaultDay: Kit? { byId(GeneratedKits.defaultDayId) }
    public static var defaultNight: Kit? { byId(GeneratedKits.defaultNightId) }

    public static func byId(_ id: String) -> Kit? {
        GeneratedKits.all.first { $0.id == id }
    }

    /// A kit's designed partner. Nil for a kit whose partner is not in this table, which is what a
    /// Secret kit looks like to a Watch that holds only one of the pair.
    public static func partnerOf(_ kit: Kit) -> Kit? { byId(kit.partner) }

    public static func type(_ pairId: String) -> KitType? { GeneratedKits.types[pairId] }

    /// Every font file the app bundles, sorted — what a launch-time self-test walks.
    public static var fontFiles: [String] {
        var files = Set<String>()
        for type in GeneratedKits.types.values {
            files.insert(type.task.file)
            for face in type.ui { files.insert(face.file) }
        }
        return files.sorted()
    }

    /// `#RRGGBB` → three channels in 0…1, or nil. Case-insensitive; the leading `#` is required,
    /// because everything in a kit has one and a bare six characters is more likely to be a mistake.
    public static func rgb(_ hex: String) -> (r: Double, g: Double, b: Double)? {
        let s = Array(hex.utf8)
        guard s.count == 7, s[0] == UInt8(ascii: "#") else { return nil }
        var v = [Double](repeating: 0, count: 3)
        for i in 0..<3 {
            guard let hi = nibble(s[1 + i * 2]), let lo = nibble(s[2 + i * 2]) else { return nil }
            v[i] = Double(hi * 16 + lo) / 255
        }
        return (v[0], v[1], v[2])
    }

    private static func nibble(_ c: UInt8) -> Int? {
        switch c {
        case UInt8(ascii: "0")...UInt8(ascii: "9"): return Int(c - UInt8(ascii: "0"))
        case UInt8(ascii: "a")...UInt8(ascii: "f"): return Int(c - UInt8(ascii: "a")) + 10
        case UInt8(ascii: "A")...UInt8(ascii: "F"): return Int(c - UInt8(ascii: "A")) + 10
        default: return nil
        }
    }
}

// ---------------------------------------------------------------- the wire shape

/// A kit as JSON, in **exactly the shape `theme.js` writes** — which is the shape
/// `test/fixtures/kits.json` holds and the shape a phone reads out of its own page when it hands the
/// two Secret kits to a Watch. One reader for all three, so there is one answer to "what does a kit
/// look like".
///
/// The reader is tolerant in the two places the web is irregular: `shapes` is a number or an array,
/// and the hairlines arrive either as `rgba()` strings (theme.js) or as the two alphas (what
/// `json` writes). Everything else is required, because a kit missing its accent is not a kit that
/// should be rendered with a default.
extension Kit {

    public init?(json: JSONValue) {
        guard let o = json.objectValue else { return nil }
        let id = o.str("id").string
        guard !id.isEmpty, let base = KitBase(rawValue: o.str("base").string),
              let lean = KitLean(rawValue: o.str("lean").string),
              let colorsObject = o["colors"]?.objectValue,
              let colors = KitColors(json: colorsObject)
        else { return nil }

        let confetti = (o["confetti"]?.arrayValue ?? []).compactMap { $0.jsString?.string }
        guard confetti.count >= 5 else { return nil }

        var shapes: [Int] = []
        if let one = o["shapes"]?.finiteNumber { shapes = [Int(one)] }
        else if let many = o["shapes"]?.arrayValue { shapes = many.compactMap { $0.finiteNumber.map(Int.init) } }
        guard !shapes.isEmpty else { return nil }

        self.init(id: id,
                  name: o.str("name").string,
                  base: base,
                  lean: lean,
                  partner: o.str("partner").string,
                  pair: o.str("pair").string,
                  secret: o.truthy("secret"),
                  colors: colors,
                  confetti: confetti,
                  shapes: shapes,
                  finaleItalic: colorsObject.str("finaleStyle").string == "italic")
    }

    /// The narrow form: the tokens this build carries and nothing else — no gradient, no shadow, no
    /// CSS animation. **Keys are inserted in sorted order**, which is not cosmetic: `JSONObject`
    /// remembers insertion order and compares it, so an unsorted write makes two encodes of the same
    /// kit unequal. `WatchLink.swift` learned that the expensive way.
    public var json: JSONValue {
        let fields: [(String, JSONValue)] = [
            ("accent", .string(colors.accent)), ("accentDeep", .string(colors.accentDeep)),
            ("accentHi", .string(colors.accentHi)), ("accentText", .string(colors.accentText)),
            ("danger", .string(colors.danger)), ("dim", .string(colors.dim)),
            ("dim2", .string(colors.dim2)), ("done", .string(colors.done)),
            ("done2", .string(colors.done2)),
            ("finaleStyle", .string(finaleItalic ? "italic" : "normal")),
            ("hairAlpha", .number(colors.hairAlpha)), ("hairHiAlpha", .number(colors.hairHiAlpha)),
            ("hairSolid", .string(colors.hairSolid)),
            ("ink", .string(colors.ink)), ("ink2", .string(colors.ink2)),
            ("ink3", .string(colors.ink3)), ("muted", .string(colors.muted)),
            ("muted2", .string(colors.muted2)), ("text", .string(colors.text))
        ]
        var colorsObject = JSONObject()
        for (key, value) in fields.sorted(by: { $0.0 < $1.0 }) { colorsObject[key] = value }

        var out = JSONObject()
        out["base"] = .string(base.rawValue)
        out["colors"] = .object(colorsObject)
        out["confetti"] = .array(confetti.map { .string($0) })
        out["id"] = .string(id)
        out["lean"] = .string(lean.rawValue)
        out["name"] = .string(name)
        out["pair"] = .string(pair)
        out["partner"] = .string(partner)
        out["secret"] = .bool(secret)
        out["shapes"] = .array(shapes.map { .number($0) })
        return .object(out)
    }
}

extension KitColors {
    init?(json o: JSONObject) {
        func hex(_ key: String) -> String? {
            let v = o.str(key).string
            return Kits.rgb(v) == nil ? nil : v
        }
        /// The hairline alpha, from either spelling: `rgba(r,g,b,a)` as theme.js writes it, or the
        /// bare number as `Kit.json` writes it.
        func alpha(_ rgbaKey: String, _ alphaKey: String) -> Double? {
            if let n = o[alphaKey]?.finiteNumber, n > 0, n < 1 { return n }
            let s = o.str(rgbaKey).string
            guard s.hasPrefix("rgba("), s.hasSuffix(")"),
                  var last = s.dropLast().split(separator: ",").last.map(String.init)
            else { return nil }
            // CSS writes a leading bare dot — theme.js's own light and pink hard-code ".16" — and
            // Swift's Double(String) is not obliged to read one.
            if last.hasPrefix(".") { last = "0" + last }
            guard let n = Double(last), n > 0, n < 1 else { return nil }
            return n
        }
        guard let ink = hex("ink"), let ink2 = hex("ink2"), let ink3 = hex("ink3"),
              let text = hex("text"), let muted = hex("muted"), let dim = hex("dim"),
              let done = hex("done"), let muted2 = hex("muted2"), let dim2 = hex("dim2"),
              let done2 = hex("done2"), let accent = hex("accent"), let accentHi = hex("accentHi"),
              let accentDeep = hex("accentDeep"), let accentText = hex("accentText"),
              let danger = hex("danger"), let hairSolid = hex("hairSolid"),
              let hairAlpha = alpha("hair", "hairAlpha"),
              let hairHiAlpha = alpha("hairHi", "hairHiAlpha")
        else { return nil }
        self.init(ink: ink, ink2: ink2, ink3: ink3, text: text, muted: muted, dim: dim, done: done,
                  muted2: muted2, dim2: dim2, done2: done2, accent: accent, accentHi: accentHi,
                  accentDeep: accentDeep, accentText: accentText, danger: danger,
                  hairSolid: hairSolid, hairAlpha: hairAlpha, hairHiAlpha: hairHiAlpha)
    }
}
