// vlib.mjs — verifier A's helpers on top of the finder's lib.mjs (copied to ./tools). Nothing here prints an id:
// console.log is wrapped so any 22+ alphanumeric run becomes <id>, and the registry reader returns counts/booleans only.
import { launch, context, freshPage, s, meta, wait, esc, openMore, openListsDetail, log, BASE, PHONE, DESKTOP, header, theme } from "./tools/lib.mjs";
export { launch, context, freshPage, s, meta, wait, esc, openMore, openListsDetail, log, BASE, PHONE, DESKTOP, header, theme };
const raw = console.log.bind(console);
console.log = (...a) => raw(...a.map(x => (typeof x === "string" ? x : JSON.stringify(x)).replace(/[0-9A-Za-z]{22,}/g, "<id>")));
export const keys = page => page.evaluate(() => Object.keys(localStorage).filter(k => k.startsWith("tf/")).map(k => k.replace(/[0-9A-Za-z]{22,}/g, "<id>")).sort());
export const localCopy = (page, id) => page.evaluate(id => { const v = localStorage.getItem("tf/v3/list/" + id); if (!v) return { present: false }; const j = JSON.parse(v); const items = Object.values((j.doc && j.doc.items) || {}); return { present: true, chars: v.length, utf8Bytes: new TextEncoder().encode(v).length, topKeys: Object.keys(j), lines: items.length, linesWithPlaintext: items.filter(i => typeof i.text === "string" && i.text.length > 0).length, plaintextChars: items.reduce((n, i) => n + (typeof i.text === "string" ? i.text.length : 0), 0) }; }, id);
/** storage's registry as counts and booleans about X — never the ids */
export const mr = async (page, X) => { const m = await meta(page); const cur = m.current; return { lists: m.lists.length, listsHasX: m.lists.includes(X), removed: m.removed ? m.removed.length : null, removedHasX: !!(m.removed && m.removed.includes(X)), unremoved: m.unremoved ? m.unremoved.length : null, dead: m.dead ? m.dead.length : null, current: cur ? (cur === X ? "X" : "other") : null }; };
export const tab = async (page, X) => { const x = await s(page); return { version: x.version, listId: x.listId ? (x.listId === X ? "X" : "other") : null, demo: x.demo, whoseOpen: !!(await page.$("#whose[open]")), welcome: await page.locator("#welcome").isVisible() }; };
/** an ordinary settings save: ⋯ → Sound (the mute toggle) when the menu is there, else the sun/moon; says which it used */
export const save = async page => { await page.bringToFront(); const more = await page.$("#more"); const vis = !!more && await more.isVisible(); const hasSound = !!(await page.$('#p-menu [data-act="sound"]')); if (vis && hasSound) { await page.click("#more"); await page.waitForSelector("#p-menu[open]"); await page.click('#p-menu [data-act="sound"]'); await wait(300); await esc(page); await wait(300); return "⋯→Sound"; } await page.evaluate(() => document.getElementById("daynight").click()); await wait(500); return "sun/moon"; };
export const removeFirst = async page => { await page.bringToFront(); await openListsDetail(page, 1); await page.click('#p-list [data-lact="remove"]'); await page.waitForSelector("#ask[open]"); await wait(200); const msg = (await page.textContent("#ask-msg")).replace(/\s+/g, " ").trim(); await page.click("#ask-ok"); await wait(1500); return msg; };
export const second = async (ctx, base, q = "") => { const p = await ctx.newPage(); p.setDefaultTimeout(8000); const errors = []; p.on("pageerror", e => errors.push(e.message)); await p.goto(base + "?transport=local" + q); await p.waitForFunction(() => window.__tf && window.__tf().listId); await wait(600); return { page: p, errors }; };
