// KitsGen — reads the two fixtures at build time and writes Kits.generated.swift: the 16 open kits
// and the 13 font pairs, as Swift literals.
//
// **It reads the fixtures and never theme.js.** That is the whole design and it is not a shortcut:
// 62 of the 314 hex tokens in the finished table appear nowhere in theme.js's source, because they
// come out of finalize() → ensure() → oklch() — cube roots, a 14-iteration gamut search, WCAG
// contrast and a 60-step lightness loop. A plugin that recomputed them would be a second
// implementation of the palette that had to match JavaScript doubles bit for bit. And `node` cannot
// be reached from a build (`/usr/bin/env -i /bin/sh -c 'command -v node'` exits 1), so the fixture
// is regenerated by hand (`node test/tools/gen-kits.mjs`) and `KitFixtureTests` is what catches
// drift — it evaluates live theme.js in a JSContext and compares.
//
// **The two Secret kits are dropped here.** The fixture has all 18; this emits the 16 that are not
// secret, so `superpink` and `birthday` are in no binary. The font *pairs* are all 13, including the
// two only the Secret kits use: a pair is not a secret, and a Secret kit that arrives at runtime
// from an unlocked phone has to be able to find its faces.
//
// It is a **prebuild** command over `/bin/sh`, for exactly ConfigGen's Phase 3 reason and with the
// same two halves forced:
//
//   * a *build* command declares the file it produces, and the plugin work directory is keyed by
//     package, target and plugin — **not by platform**. The moment two targets in one project link
//     this package (the iPhone app and the Watch app both do), one build plans the same producer
//     twice and the build system refuses: "Multiple commands produce …". A prebuild command hands
//     over a *directory* to glob, so the collision cannot arise.
//   * "a prebuild command cannot use executables built from source" — the build system's own words —
//     so the writer is `/bin/sh`.
//
// The generated source goes across as one `/bin/sh` argument and is written with `printf '%s'`
// rather than a heredoc: a heredoc that expands (ConfigGen's, which is fine for two short strings)
// would eat a `$` or a backtick in 13 KB of Swift, and one that does not expand cannot see the
// argument at all. Measured: the source is ~28 KB against an ARG_MAX of 1 MB.
import Foundation
import PackagePlugin

@main
struct KitsGen: BuildToolPlugin {

    func createBuildCommands(context: PluginContext, target: Target) throws -> [Command] {
        // apple/TodaysFiveCore → apple → the repo root, where test/fixtures lives. The identical
        // two-level walk ConfigGen does, and for the identical reason: the package knows where it is
        // and the repo is two levels up from it.
        let repo = context.package.directoryURL
            .deletingLastPathComponent()
            .deletingLastPathComponent()

        let kits = Self.load(repo.appending(path: "test/fixtures/kits.json"))
        let fonts = Self.load(repo.appending(path: "test/fixtures/watch-fonts.json"))
        let source = Self.swift(kits: kits, fonts: fonts)

        let out = context.pluginWorkDirectoryURL.appending(path: "Kits.generated.swift")
        let script = """
        mkdir -p "$(dirname "$1")"
        printf '%s' "$2" > "$1"
        """
        return [
            .prebuildCommand(
                displayName: "Reading the kit table",
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", script, "kits-gen", out.path(percentEncoded: false), source],
                outputFilesDirectory: context.pluginWorkDirectoryURL
            )
        ]
    }

    // ---------------------------------------------------------------- reading

    static func load(_ url: URL) -> [String: Any] {
        guard let data = try? Data(contentsOf: url),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else { return [:] }
        return object
    }

    // ---------------------------------------------------------------- writing

    static func swift(kits: [String: Any], fonts: [String: Any]) -> String {
        let all = (kits["kits"] as? [[String: Any]]) ?? []
        let open = all.filter { ($0["secret"] as? Bool) != true }
        let pairs = (fonts["pairs"] as? [String: Any]) ?? [:]

        var lines: [String] = []
        lines.append("""
        // Generated at build time by the KitsGen plugin from test/fixtures/kits.json and
        // test/fixtures/watch-fonts.json. Do not edit — regenerate the fixtures with
        // `node test/tools/gen-kits.mjs` and `python3 apple/tools/gen-watch-fonts.py`.
        //
        // The two Secret kits are deliberately absent: the fixture holds 18 and this holds \(open.count).
        // Kits.swift says what each token is and what was dropped on the way here.

        enum GeneratedKits {
        """)

        lines.append("    static let all: [Kit] = [")
        for kit in open { lines.append(kitLiteral(kit)) }
        lines.append("    ]\n")

        lines.append("    static let types: [String: KitType] = [")
        for id in pairs.keys.sorted() {
            guard let pair = pairs[id] as? [String: Any] else { continue }
            lines.append(typeLiteral(id: id, pair: pair))
        }
        lines.append("    ]\n")

        lines.append("    static let dayIds: [String] = \(list(kits["day"] as? [String] ?? []))")
        lines.append("    static let nightIds: [String] = \(list(kits["night"] as? [String] ?? []))")
        let slot = (kits["slotDefault"] as? [String: String]) ?? [:]
        lines.append("    static let defaultDayId = \(quote(slot["day"] ?? ""))")
        lines.append("    static let defaultNightId = \(quote(slot["night"] ?? ""))")
        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }

    static func kitLiteral(_ kit: [String: Any]) -> String {
        let colors = (kit["colors"] as? [String: Any]) ?? [:]
        func hex(_ key: String) -> String { quote((colors[key] as? String) ?? "") }
        let confetti = ((kit["confetti"] as? [String]) ?? []).map(quote).joined(separator: ", ")
        let shapes = ((kit["shapes"] as? [Int]) ?? []).map(String.init).joined(separator: ", ")
        let italic = (colors["finaleStyle"] as? String) == "italic"
        return """
            Kit(id: \(quote(kit["id"] as? String ?? "")), name: \(quote(kit["name"] as? String ?? "")),
                base: .\(kit["base"] as? String ?? "dark"), lean: .\(kit["lean"] as? String ?? "day"),
                partner: \(quote(kit["partner"] as? String ?? "")), pair: \(quote(kit["pair"] as? String ?? "")),
                secret: false,
                colors: KitColors(ink: \(hex("ink")), ink2: \(hex("ink2")), ink3: \(hex("ink3")),
                                  text: \(hex("text")), muted: \(hex("muted")), dim: \(hex("dim")), done: \(hex("done")),
                                  muted2: \(hex("muted2")), dim2: \(hex("dim2")), done2: \(hex("done2")),
                                  accent: \(hex("accent")), accentHi: \(hex("accentHi")),
                                  accentDeep: \(hex("accentDeep")), accentText: \(hex("accentText")),
                                  danger: \(hex("danger")), hairSolid: \(hex("hairSolid")),
                                  hairAlpha: \(alpha(colors["hair"])), hairHiAlpha: \(alpha(colors["hairHi"]))),
                confetti: [\(confetti)], shapes: [\(shapes)], finaleItalic: \(italic)),
        """
    }

    static func typeLiteral(id: String, pair: [String: Any]) -> String {
        let task = (pair["task"] as? [String: Any]) ?? [:]
        let ui = (pair["ui"] as? [String: Any]) ?? [:]
        let uiFaces = ((ui["faces"] as? [[String: Any]]) ?? []).map(faceLiteral).joined(separator: ", ")
        let taskFace = ((task["faces"] as? [[String: Any]]) ?? []).first.map(faceLiteral) ?? "KitFace(postScriptName: \"\", family: \"\", weight: 400, file: \"\")"
        return """
            \(quote(id)): KitType(id: \(quote(id)), name: \(quote(pair["name"] as? String ?? "")),
                task: \(taskFace),
                ui: [\(uiFaces)],
                tracking: \(em(pair["ls"])), lineHeight: \(number(pair["lh"]))),
        """
    }

    static func faceLiteral(_ face: [String: Any]) -> String {
        "KitFace(postScriptName: \(quote(face["postScriptName"] as? String ?? "")), "
        + "family: \(quote(face["family"] as? String ?? "")), "
        + "weight: \(face["weight"] as? Int ?? 400), "
        + "file: \(quote(face["file"] as? String ?? "")))"
    }

    // ---------------------------------------------------------------- small conversions

    /// `hair` and `hairHi` are `rgba(r,g,b,a)` and always an alpha over the kit's own `--text` —
    /// gen-kits.mjs asserts that of all 18 kits, because Pink writes .16/.42 by hand despite a dark
    /// base and deriving the alpha from `base` would give it the wrong hairline. Only the alpha
    /// crosses; the colour is `text`.
    static func alpha(_ value: Any?) -> String {
        guard let s = value as? String, s.hasSuffix(")"),
              let last = s.dropLast().split(separator: ",").last,
              let n = decimal(String(last)) else { return "0" }
        return String(n)
    }

    /// theme.js's `ls`: "-.025em", "0", "-.005em" → a Double in em.
    static func em(_ value: Any?) -> String {
        String(decimal(((value as? String) ?? "0").replacingOccurrences(of: "em", with: "")) ?? 0)
    }

    /// CSS writes a leading bare dot — ".16", "-.025" — and Swift's `Double(String)` is not obliged
    /// to read one. The zero goes back in first.
    static func decimal(_ text: String) -> Double? {
        var s = text.trimmingCharacters(in: .whitespaces)
        if s.hasPrefix(".") { s = "0" + s }
        if s.hasPrefix("-.") { s = "-0" + s.dropFirst() }
        return Double(s)
    }

    static func number(_ value: Any?) -> String {
        if let d = value as? Double { return String(d) }
        if let i = value as? Int { return String(Double(i)) }
        return "1"
    }

    static func list(_ values: [String]) -> String { "[" + values.map(quote).joined(separator: ", ") + "]" }

    /// A Swift string literal. Nothing in either fixture carries a quote or a backslash today —
    /// family names, kit names and hexes — but a generator that would emit broken Swift if one ever
    /// did is a generator that fails at build time for a reason nobody can see from the diff.
    static func quote(_ s: String) -> String {
        "\"" + s.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"") + "\""
    }
}
